
name: Manual Matrix Job

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      container-image:
        description: 'Docker container image'
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image:  ${{ github.event.inputs.container-image }}

    strategy:
      matrix:
        tag: [v0.3.12, v0.3.28, v0.4.0, v0.4.1290, v0.4.1802, v0.4.1803, v0.4.2059, v0.4.2307, v0.4.267, v0.4.3075, v0.4.3328-internal-prod-tooling, v0.4.773, v0.4.9, v0.5.2048-test, v0.5.2304-rc, v0.5.2306, v0.5.2560-rc, v0.5.2560-rc1]

    steps:
    - name: Run Docker container
      run: |
        git clone --branch ${{ matrix.tag }} https://github.com/Cypherock/x1_wallet_firmware.git --recurse-submodules --depth 1
        ls x1_wallet_firmware
        cd x1_wallet_firmware
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE:STRING="Release" -DFIRMWARE_TYPE="Main" -DCMAKE_BUILD_PLATFORM:STRING="Device" -G "Ninja" ../
        ninja
        sha256sum Cypherock-Main.bin

